FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["AccountServices.csproj", "./"]
RUN dotnet restore "AccountServices.csproj"
COPY . .
RUN dotnet build "AccountServices.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "AccountServices.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "AccountServices.dll"] 